name: Update flake.lock
on:
  workflow_dispatch:
  schedule:
    - cron: '30 0 * * 0'

permissions:
  contents: write

jobs:
  update-flake-lock:
    uses: msfjarvis/shared-workflows/.github/workflows/update-flake-lock.yml@12b90e67ec0ea0bce2b65c85597b80e9e41feab1 # main
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
