name: Update flake.lock
on:
  workflow_dispatch:
  schedule:
    - cron: '30 0 * * 0'

permissions:
  contents: write

jobs:
  update-flake-lock:
    uses: msfjarvis/shared-workflows/.github/workflows/update-flake-lock.yml@9fcb820f947c9c68ebefde009b89187e31e7b664 # main
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
