name: Update flake.lock
on:
  workflow_dispatch:
  schedule:
    - cron: '30 0 * * 0'

permissions:
  contents: write

jobs:
  update-flake-lock:
    uses: msfjarvis/shared-workflows/.github/workflows/update-flake-lock.yml@a5f13ca65cf3ab5ceca8496c76dbf6d7b1bb4dc2 # main
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
