on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

name: Check Rust code
jobs:
  check:
    uses: msfjarvis/shared-workflows/.github/workflows/test-flakes-project.yml@4dae98c229ca5fd34b1a5a33228be693248e4c88 # main
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      cachix-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
